CREATE TABLE accounts (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR2(20) NOT NULL UNIQUE,
    customer_id NUMBER NOT NULL,
    branch_id NUMBER NOT NULL,
    account_type VARCHAR2(30) NOT NULL,
    account_status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    opening_date DATE NOT NULL,
    balance NUMBER(15,2) DEFAULT 0 NOT NULL,

    CONSTRAINT fk_account_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id),

    CONSTRAINT fk_account_branch
        FOREIGN KEY (branch_id)
        REFERENCES branches(branch_id),

    CONSTRAINT chk_account_type
        CHECK (account_type IN ('SAVINGS', 'CURRENT', 'SALARY', 'FIXED DEPOSIT')),

    CONSTRAINT chk_account_status
        CHECK (account_status IN ('ACTIVE', 'INACTIVE', 'BLOCKED', 'CLOSED')),

    CONSTRAINT chk_account_balance
        CHECK (balance >= 0)
);