CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_number VARCHAR2(20) NOT NULL UNIQUE,
    customer_name VARCHAR2(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    mobile_number VARCHAR2(15) NOT NULL UNIQUE,
    email VARCHAR2(100) UNIQUE,
    gender VARCHAR2(10),
    city VARCHAR2(50) NOT NULL,
    state VARCHAR2(50) NOT NULL,
    kyc_status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    customer_status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT chk_customer_gender
        CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),

    CONSTRAINT chk_kyc_status
        CHECK (kyc_status IN ('PENDING', 'VERIFIED', 'REJECTED')),

    CONSTRAINT chk_customer_status
        CHECK (customer_status IN ('ACTIVE', 'INACTIVE', 'BLOCKED'))
);
