CREATE TABLE transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_reference VARCHAR2(30) NOT NULL UNIQUE,
    account_id NUMBER NOT NULL,
    transaction_type VARCHAR2(20) NOT NULL,
    transaction_amount NUMBER(15,2) NOT NULL,
    transaction_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    transaction_status VARCHAR2(20) DEFAULT 'SUCCESS' NOT NULL,
    description VARCHAR2(200),

    CONSTRAINT fk_transaction_account
        FOREIGN KEY (account_id)
        REFERENCES accounts(account_id),

    CONSTRAINT chk_transaction_type
        CHECK (transaction_type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER', 'INTEREST')),

    CONSTRAINT chk_transaction_amount
        CHECK (transaction_amount > 0),

    CONSTRAINT chk_transaction_status
        CHECK (transaction_status IN ('SUCCESS', 'FAILED', 'PENDING'))
);