CREATE TABLE branches (
    branch_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_code VARCHAR2(20) NOT NULL UNIQUE,
    branch_name VARCHAR2(100) NOT NULL,
    city VARCHAR2(50) NOT NULL,
    state VARCHAR2(50) NOT NULL,
    ifsc_code VARCHAR2(20) NOT NULL UNIQUE,
    branch_type VARCHAR2(30) DEFAULT 'REGULAR' NOT NULL,
    opening_date DATE NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,

    CONSTRAINT chk_branch_type
        CHECK (branch_type IN ('REGULAR', 'HEAD OFFICE', 'RURAL', 'URBAN')),

    CONSTRAINT chk_branch_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);


